[package]
name = "rust_erizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = "*"
minifb = "0.23"
glam = "0.22.0"
image = "*"
