name: Build Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Checks whether the project is formatted correctly
    - name: Formatter
      run: cargo fmt --all -- --check
    
    # Check whether the project Builds
    - name: Builds
      run: cargo build --verbose
    
    # Checks whether there are no clippy warnings 
    - name: No Warnings (warnings)
      run: cargo clippy -- -D warnings
    
    # Checks whether all tests are successful
    - name: Run tests
      run: cargo test --verbose
    
